parameters:
- name: windowsPool
  type: object
  default:
    vmImage: windows-2022
- name: EnableAPIScan
  type: boolean
  default: false

jobs:
- job: Windows
  pool: ${{ parameters.windowsPool }}
  variables:
  - ${{ if eq(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9') }}:
    # https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/25351/APIScan-step-by-step-guide-to-setting-up-a-Pipeline
    - group: VSCloudServices-APIScan
  steps:
  - checkout: self
    clean: true

  - ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
    - template: schedule-only-steps.yml

  - template: install-dependencies.yml

  - powershell: '& (./azure-pipelines/Get-nbgv.ps1) cloud -ca'
    displayName: Set build number

  - ${{ if eq(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9') }}:
    - template: microbuild.before.yml

  - template: dotnet.yml

  - ${{ if eq(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9') }}:
    - template: microbuild.after.yml
      parameters:
        EnableAPIScan: ${{ parameters.EnableAPIScan }}

- job: WrapUp
  dependsOn:
  - Windows
  pool:
    vmImage: Ubuntu 20.04
  condition: succeededOrFailed()
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
    parameters:
      initArgs: -NoRestore
  - template: publish-codecoverage.yml
